In [13]:
import numpy as np

# 1. Crear matriz 3x3 con números del 1 al 9
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("Matriz A original:\n", A)

# 2. Suma 10 a cada elemento
A_plus_10 = A + 10
print("\nMatriz A + 10:\n", A_plus_10)

# Multiplica la matriz por 2
A_times_2 = A * 2
print("\nMatriz A * 2:\n", A_times_2)

# 3. Selección condicional: elementos mayores a 5
condicional = A[A > 5]
print("\nElementos mayores a 5:", condicional)

# 4. Asignación: referencia vs copia
B = A  # referencia
B[0,0] = 999
print("\nMatriz B después de modificar B[0,0] =", B[0,0])
print("¿Cambió A?\n", A)

# Ahora prueba con copia
A[0,0] = 1  # restaurar A
B = A.copy()  # copia independiente
B[0,0] = 888
print("\nB modificado con copia:", B)
print("¿Cambió A?\n", A)


Matriz A original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz A + 10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Matriz A * 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Elementos mayores a 5: [6 7 8 9]

Matriz B después de modificar B[0,0] = 999
¿Cambió A?
 [[999   2   3]
 [  4   5   6]
 [  7   8   9]]

B modificado con copia: [[888   2   3]
 [  4   5   6]
 [  7   8   9]]
¿Cambió A?
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
import numpy as np

# 1. np.arange() y reshape()
x = np.arange(1, 17)
print("Arreglo x:", x)
x_4x4 = x.reshape(4,4)
print("\nMatriz 4x4:\n", x_4x4)

# 2. np.linspace()
lin = np.linspace(0, 100, 10)
print("\nArreglo con linspace:", lin)

# 3. np.random.randint()
rand_matrix = np.random.randint(1, 21, size=(3,3))
print("\nMatriz aleatoria 3x3:\n", rand_matrix)

# 4. Aplicar np.sqrt() y np.log()
print("\nRaíz cuadrada matriz aleatoria:\n", np.sqrt(rand_matrix))
print("\nLogaritmo matriz aleatoria:\n", np.log(rand_matrix))

# 5. Diferencias al aplicar funciones
# np.sqrt() sobre enteros devuelve flotantes
print("\nTipo original:", rand_matrix.dtype)
sqrt_result = np.sqrt(rand_matrix)
print("Tipo después de sqrt:", sqrt_result.dtype)


Arreglo x: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

Matriz 4x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Arreglo con linspace: [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]

Matriz aleatoria 3x3:
 [[ 8 19 12]
 [11  2  5]
 [12  6  9]]

Raíz cuadrada matriz aleatoria:
 [[2.82842712 4.35889894 3.46410162]
 [3.31662479 1.41421356 2.23606798]
 [3.46410162 2.44948974 3.        ]]

Logaritmo matriz aleatoria:
 [[2.07944154 2.94443898 2.48490665]
 [2.39789527 0.69314718 1.60943791]
 [2.48490665 1.79175947 2.19722458]]

Tipo original: int64
Tipo después de sqrt: float64
